name: Quality Assurance
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  lint-format-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node & NPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Check formatting
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node & NPM
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm run test:unit

      - name: Rendering tests
        run: npm run test:rendering
